### PR TITLE
Feature/add information on solo mining under the tables with addresses

### PR DESCRIPTION
**Pull request by AndrewMatsiash**

### CODE REVIEW

**Comment by AndrewMatsiash** [comment]
Screenshot 2024-07-26 at 15 54 24
Screenshot 2024-07-26 at 16 10 35
Screenshot 2024-07-26 at 16 10 43

**Comment by AndrewMatsiash** [comment]
Screenshot 2024-07-29 at 12 38 39

**Comment by nnslvp** [comment]
выдели плз Solo mining черный жирным

**Comment by AndrewMatsiash** [comment]
Screenshot 2024-07-29 at 18 12 42

**Comment by AndrewMatsiash** [comment]
сделал как в старом

**Review by nnslvp — APPROVED** [review]

**Pull request merged**
